# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://127.0.0.1:8000/scan/zip
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="test.zip"
Content-Type: application/zip

< ./test.zip
--boundary--

###
