# suggestion_rules.py
# Rule-based keyword mappings for AI Suggestion Assistant in Compliance Chain Links.
# Used by SuggestionService to score relevance between chain entities.

# Asset type keywords → risk category keywords + boost terms
# Keys are lowercase substrings matched against asset_type_name
ASSET_TYPE_TO_RISK_KEYWORDS = {
    "server": ["unauthorized access", "denial of service", "data breach", "misconfiguration", "privilege escalation", "patch management"],
    "database": ["data breach", "sql injection", "unauthorized access", "data loss", "backup failure", "encryption"],
    "network": ["denial of service", "man-in-the-middle", "unauthorized access", "network intrusion", "firewall", "segmentation"],
    "application": ["injection", "cross-site", "authentication", "session", "input validation", "api security"],
    "web": ["cross-site scripting", "injection", "authentication bypass", "session hijacking", "csrf", "api"],
    "api": ["injection", "authentication", "rate limiting", "data exposure", "api security", "authorization"],
    "cloud": ["misconfiguration", "data breach", "identity", "access management", "shared responsibility", "encryption"],
    "iot": ["firmware", "default credentials", "physical tampering", "communication", "update mechanism", "authentication"],
    "mobile": ["data leakage", "insecure storage", "authentication", "communication", "reverse engineering", "tampering"],
    "endpoint": ["malware", "unauthorized access", "data leakage", "patch management", "encryption", "physical"],
    "firmware": ["supply chain", "tampering", "update mechanism", "vulnerability", "integrity", "authentication"],
    "hardware": ["physical tampering", "supply chain", "environmental", "theft", "destruction", "electromagnetic"],
    "software": ["vulnerability", "patch management", "license", "supply chain", "malware", "integrity"],
    "data": ["data breach", "data loss", "unauthorized access", "encryption", "classification", "retention"],
    "user": ["social engineering", "phishing", "insider threat", "credential", "awareness", "privilege"],
    "service": ["availability", "denial of service", "dependency", "sla", "continuity", "third party"],
}

# CIA rating levels → boosted risk keywords
# When an asset has high CIA ratings, these keywords get boosted in scoring
CIA_RISK_WEIGHTING = {
    "confidentiality": {
        "high": ["data breach", "unauthorized access", "data exposure", "encryption", "classification", "leakage", "privacy"],
        "medium": ["access control", "authentication", "data protection"],
        "low": [],
    },
    "integrity": {
        "high": ["tampering", "injection", "data corruption", "integrity", "validation", "modification", "supply chain"],
        "medium": ["input validation", "checksums", "audit trail"],
        "low": [],
    },
    "availability": {
        "high": ["denial of service", "availability", "redundancy", "disaster recovery", "continuity", "resilience", "failover"],
        "medium": ["backup", "monitoring", "capacity"],
        "low": [],
    },
}

# Risk keywords → control code prefixes
# Maps risk description keywords to likely control code prefixes
RISK_CATEGORY_TO_CONTROL_PREFIX = {
    "access": ["IAM", "ACC", "AC"],
    "authentication": ["IAM", "ACC", "AU", "AC"],
    "authorization": ["IAM", "ACC", "AC"],
    "identity": ["IAM", "ACC", "AC"],
    "credential": ["IAM", "ACC", "AC"],
    "encryption": ["DCH", "CRY", "SC", "DP"],
    "data breach": ["DCH", "DLP", "DP", "IR"],
    "data loss": ["DCH", "DLP", "BKP", "DP"],
    "data protection": ["DCH", "DLP", "DP"],
    "network": ["NES", "NET", "SC", "FW"],
    "firewall": ["NES", "NET", "FW"],
    "segmentation": ["NES", "NET", "SC"],
    "intrusion": ["NES", "IDS", "MON"],
    "denial of service": ["NES", "AVL", "CAP"],
    "malware": ["EPP", "AV", "MAL"],
    "vulnerability": ["VLM", "PAT", "VM"],
    "patch": ["VLM", "PAT", "CM"],
    "injection": ["SWD", "INP", "SC"],
    "cross-site": ["SWD", "INP", "WEB"],
    "input validation": ["SWD", "INP", "SC"],
    "api": ["SWD", "API", "SC"],
    "monitoring": ["MON", "LOG", "SIM"],
    "logging": ["MON", "LOG", "AU"],
    "audit": ["MON", "LOG", "AU", "COM"],
    "backup": ["BKP", "BCM", "DR"],
    "disaster": ["BCM", "DR", "BKP"],
    "continuity": ["BCM", "DR", "BCP"],
    "physical": ["PHY", "PE", "PS"],
    "social engineering": ["SAT", "AWR", "HR"],
    "phishing": ["SAT", "AWR", "EM"],
    "awareness": ["SAT", "AWR", "HR"],
    "training": ["SAT", "AWR", "HR", "HRM"],
    "insider": ["HRM", "IAM", "MON"],
    "supply chain": ["SCM", "TPM", "VEN"],
    "third party": ["TPM", "VEN", "SCM"],
    "vendor": ["TPM", "VEN", "SCM"],
    "configuration": ["CM", "SEC", "HRD"],
    "misconfiguration": ["CM", "SEC", "HRD"],
    "compliance": ["COM", "GRC", "POL"],
    "incident": ["IR", "INC", "MON"],
    "response": ["IR", "INC", "BCM"],
    "firmware": ["SWD", "FW", "PAT", "SCM"],
    "iot": ["IOT", "NES", "IAM", "SWD"],
    "cloud": ["CLD", "IAM", "DCH", "CM"],
    "mobile": ["MOB", "MDM", "DCH"],
}

# Control prefix → policy keyword patterns
# Maps control code prefixes to policy-relevant keywords
CONTROL_PREFIX_TO_POLICY_KEYWORDS = {
    "IAM": ["access control", "identity", "authentication", "authorization", "password", "account management"],
    "ACC": ["access control", "identity", "authentication", "authorization"],
    "AC": ["access control", "identity", "authorization"],
    "DCH": ["data protection", "data classification", "encryption", "privacy", "data handling"],
    "DLP": ["data loss prevention", "data protection", "information security"],
    "DP": ["data protection", "privacy", "personal data"],
    "CRY": ["encryption", "cryptography", "key management"],
    "NES": ["network security", "firewall", "segmentation", "perimeter"],
    "NET": ["network security", "network management", "connectivity"],
    "FW": ["firewall", "network security", "perimeter defense"],
    "SC": ["secure coding", "security configuration", "system security"],
    "EPP": ["endpoint protection", "antivirus", "malware prevention"],
    "AV": ["antivirus", "malware", "endpoint protection"],
    "MAL": ["malware protection", "antivirus", "endpoint security"],
    "VLM": ["vulnerability management", "patch management", "security assessment"],
    "PAT": ["patch management", "update management", "change management"],
    "VM": ["vulnerability management", "scanning", "remediation"],
    "SWD": ["software development", "secure development", "sdlc", "application security"],
    "INP": ["input validation", "secure coding", "application security"],
    "API": ["api security", "interface security", "integration"],
    "WEB": ["web security", "application security", "web application"],
    "MON": ["monitoring", "logging", "security monitoring", "siem"],
    "LOG": ["logging", "audit trail", "monitoring"],
    "SIM": ["security information", "event management", "monitoring"],
    "AU": ["audit", "logging", "compliance", "audit trail"],
    "BKP": ["backup", "recovery", "data protection", "business continuity"],
    "BCM": ["business continuity", "disaster recovery", "resilience"],
    "DR": ["disaster recovery", "backup", "business continuity"],
    "BCP": ["business continuity", "continuity planning"],
    "PHY": ["physical security", "facility", "environmental"],
    "PE": ["physical security", "physical environment"],
    "PS": ["physical security", "personnel security"],
    "SAT": ["security awareness", "training", "education"],
    "AWR": ["awareness", "training", "security culture"],
    "HR": ["human resources", "personnel security", "onboarding"],
    "HRM": ["human resources", "personnel", "staff management"],
    "SCM": ["supply chain", "vendor management", "third party risk"],
    "TPM": ["third party", "vendor", "supply chain", "outsourcing"],
    "VEN": ["vendor management", "supplier", "third party"],
    "CM": ["change management", "configuration management", "change control"],
    "SEC": ["security configuration", "hardening", "baseline"],
    "HRD": ["hardening", "security configuration", "baseline"],
    "COM": ["compliance", "regulatory", "governance"],
    "GRC": ["governance", "risk", "compliance"],
    "POL": ["policy", "standard", "procedure", "governance"],
    "IR": ["incident response", "incident management", "security incident"],
    "INC": ["incident management", "incident response", "event"],
    "IOT": ["iot security", "device security", "embedded"],
    "CLD": ["cloud security", "cloud governance", "saas", "iaas"],
    "MOB": ["mobile security", "mobile device", "byod"],
    "MDM": ["mobile device management", "device management"],
}

# Policy keyword clusters → objective keyword patterns
# Maps policy title/body keywords to relevant objective keywords
POLICY_TO_OBJECTIVE_KEYWORDS = {
    "access control": ["access", "authentication", "identity", "authorization", "privilege", "account", "password", "credential"],
    "data protection": ["data", "privacy", "personal data", "confidential", "classification", "encryption", "storage", "retention"],
    "data classification": ["classification", "labeling", "handling", "sensitivity", "data categories"],
    "network security": ["network", "firewall", "segmentation", "perimeter", "intrusion", "traffic", "communication"],
    "endpoint": ["endpoint", "workstation", "device", "antivirus", "malware", "protection"],
    "vulnerability": ["vulnerability", "patch", "update", "remediation", "scanning", "assessment"],
    "incident": ["incident", "response", "detection", "notification", "escalation", "recovery", "breach"],
    "business continuity": ["continuity", "disaster", "recovery", "backup", "resilience", "availability"],
    "awareness": ["awareness", "training", "education", "competence", "security culture", "personnel"],
    "physical security": ["physical", "facility", "environmental", "access control", "perimeter", "surveillance"],
    "supply chain": ["supply chain", "vendor", "supplier", "third party", "outsourcing", "procurement"],
    "change management": ["change", "configuration", "deployment", "release", "version"],
    "compliance": ["compliance", "regulatory", "legal", "requirement", "obligation", "audit", "certification"],
    "risk management": ["risk", "assessment", "treatment", "appetite", "tolerance", "mitigation"],
    "cryptography": ["encryption", "cryptographic", "key management", "certificate", "hashing", "digital signature"],
    "secure development": ["development", "coding", "testing", "sdlc", "review", "deployment", "application"],
    "monitoring": ["monitoring", "logging", "alerting", "detection", "surveillance", "audit trail", "event"],
    "governance": ["governance", "policy", "standard", "procedure", "framework", "management system"],
    "privacy": ["privacy", "personal data", "consent", "data subject", "processing", "gdpr", "data protection"],
    "cloud": ["cloud", "saas", "iaas", "paas", "virtual", "containerization", "shared responsibility"],
    "mobile": ["mobile", "device", "byod", "remote", "wireless"],
    "asset management": ["asset", "inventory", "classification", "ownership", "lifecycle"],
    "human resources": ["personnel", "employee", "hiring", "termination", "role", "responsibility", "screening"],
}
