"""Add created_by columns to policies, risks, and products

Revision ID: 0c49ce9ae4fa
Revises: 3f06c48743bc
Create Date: 2025-09-24 15:38:43.900580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '0c49ce9ae4fa'
down_revision: Union[str, None] = '3f06c48743bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name: str) -> bool:
    """Check if a table exists in the database"""
    conn = op.get_bind()
    inspector = inspect(conn)
    return table_name in inspector.get_table_names()


def column_exists(table_name: str, column_name: str) -> bool:
    """Check if a column exists in a table"""
    conn = op.get_bind()
    inspector = inspect(conn)
    if not table_exists(table_name):
        return False
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add columns if tables exist and columns don't already exist
    if table_exists('policies') and not column_exists('policies', 'created_by'):
        op.add_column('policies', sa.Column('created_by', sa.UUID(), nullable=True))
        op.create_foreign_key(None, 'policies', 'users', ['created_by'], ['id'])

    if table_exists('products') and not column_exists('products', 'created_by'):
        op.add_column('products', sa.Column('created_by', sa.UUID(), nullable=True))
        op.create_foreign_key(None, 'products', 'users', ['created_by'], ['id'])

    if table_exists('risks') and not column_exists('risks', 'created_by'):
        op.add_column('risks', sa.Column('created_by', sa.UUID(), nullable=True))
        op.create_foreign_key(None, 'risks', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risks', type_='foreignkey')
    op.drop_column('risks', 'created_by')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'created_by')
    op.drop_constraint(None, 'policies', type_='foreignkey')
    op.drop_column('policies', 'created_by')
    # ### end Alembic commands ###
