"""add_organization_framework_permissions_table

Revision ID: 2e4ac16990ec
Revises: 0c49ce9ae4fa
Create Date: 2025-09-25 08:55:23.535498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '2e4ac16990ec'
down_revision: Union[str, None] = '0c49ce9ae4fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name: str) -> bool:
    """Check if a table exists in the database"""
    conn = op.get_bind()
    inspector = inspect(conn)
    return table_name in inspector.get_table_names()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only create table if it doesn't exist and required tables exist
    if not table_exists('organization_framework_permissions') and table_exists('frameworks') and table_exists('organisations'):
        op.create_table('organization_framework_permissions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('framework_id', sa.UUID(), nullable=False),
        sa.Column('can_seed', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ),
        sa.ForeignKeyConstraint(['organization_id'], ['organisations.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_framework_permissions')
    # ### end Alembic commands ###
