"""Add pdf_downloads table

Revision ID: 31559c170259
Revises: a215a1e7036a
Create Date: 2025-11-10 16:30:28.666359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31559c170259'
down_revision: Union[str, None] = 'a215a1e7036a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table exists before creating
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if 'pdf_downloads' not in inspector.get_table_names():
        op.create_table(
            'pdf_downloads',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('user_id', sa.UUID(), nullable=False),
            sa.Column('email', sa.String(length=255), nullable=False),
            sa.Column('pdf_type', sa.String(length=100), nullable=False),
            sa.Column('download_timestamp', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()')),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf_downloads')
    # ### end Alembic commands ###
