"""add_question_correlations_table

Revision ID: 3745a5e751fb
Revises: e6e3a716fdc5
Create Date: 2025-09-25 11:50:33.697911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3745a5e751fb'
down_revision: Union[str, None] = 'e6e3a716fdc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
