"""add_missing_last_updated_by_audit_columns

Revision ID: 3f06c48743bc
Revises: 71b21f2e698e
Create Date: 2025-09-24 11:52:05.114920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '3f06c48743bc'
down_revision: Union[str, None] = '71b21f2e698e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name: str) -> bool:
    """Check if a table exists in the database"""
    conn = op.get_bind()
    inspector = inspect(conn)
    return table_name in inspector.get_table_names()


def column_exists(table_name: str, column_name: str) -> bool:
    """Check if a column exists in a table"""
    conn = op.get_bind()
    inspector = inspect(conn)
    if not table_exists(table_name):
        return False
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add columns if tables exist and columns don't already exist
    if table_exists('policies') and not column_exists('policies', 'last_updated_by'):
        op.add_column('policies', sa.Column('last_updated_by', sa.UUID(), nullable=True))
        op.create_foreign_key(None, 'policies', 'users', ['last_updated_by'], ['id'])

    if table_exists('products') and not column_exists('products', 'last_updated_by'):
        op.add_column('products', sa.Column('last_updated_by', sa.UUID(), nullable=True))
        op.create_foreign_key(None, 'products', 'users', ['last_updated_by'], ['id'])

    if table_exists('risks') and not column_exists('risks', 'last_updated_by'):
        op.add_column('risks', sa.Column('last_updated_by', sa.UUID(), nullable=True))
        op.create_foreign_key(None, 'risks', 'users', ['last_updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risks', type_='foreignkey')
    op.drop_column('risks', 'last_updated_by')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'last_updated_by')
    op.drop_constraint(None, 'policies', type_='foreignkey')
    op.drop_column('policies', 'last_updated_by')
    # ### end Alembic commands ###
