"""add_scanner_history_table

Revision ID: bcc2f3b453ed
Revises: 31559c170259
Create Date: 2025-11-11 12:10:17.544127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc2f3b453ed'
down_revision: Union[str, None] = '31559c170259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scanner_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scanner_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('organisation_name', sa.String(length=255), nullable=True),
    sa.Column('scan_target', sa.String(length=500), nullable=False),
    sa.Column('scan_type', sa.String(length=100), nullable=True),
    sa.Column('scan_config', sa.Text(), nullable=True),
    sa.Column('results', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scan_duration', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scanner_history')
    # ### end Alembic commands ###
