import json
import os
import uuid
import importlib
import logging
from datetime import datetime
from typing import List, Dict, Optional

from sqlalchemy.orm import Session

from ..repositories import regulatory_monitor_repository as repo
from ..models.models import RegulatoryChange

logger = logging.getLogger(__name__)

# Base directory for seed update files
SEEDS_BASE_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "seeds", "updates")


class SeedFileWriterService:
    """
    Generates and writes BaseFrameworkUpdate subclass Python files
    from approved regulatory changes.
    """

    @staticmethod
    def generate_update_file(
        framework_type: str,
        version: int,
        changes: List[RegulatoryChange],
        description: str = None
    ) -> str:
        """
        Render a BaseFrameworkUpdate subclass from approved changes.
        Uses string templates following the exact structure of cra_update_1.py.
        """
        class_name = SeedFileWriterService._make_class_name(framework_type, version)
        desc = description or f"Regulatory monitor auto-generated update (version {version})"

        # Categorize changes
        new_questions = []
        new_chapters = []
        new_objectives = []
        updated_objectives = []
        updated_questions = []

        for change in changes:
            proposed = json.loads(change.proposed_value) if change.proposed_value else {}

            if change.change_type == "new_question":
                new_questions.append(proposed)
            elif change.change_type == "new_chapter":
                new_chapters.append(proposed)
            elif change.change_type == "new_objective":
                new_objectives.append(proposed)
            elif change.change_type == "update_objective":
                obj = {"subchapter": change.entity_identifier}
                obj.update(proposed)
                updated_objectives.append(obj)
            elif change.change_type == "update_question":
                q = {"question_id": change.entity_identifier}
                q.update(proposed)
                updated_questions.append(q)

        # Generate file content
        lines = [
            'from typing import List, Dict',
            'from ..base_framework_update import BaseFrameworkUpdate',
            '',
            '',
            f'class {class_name}(BaseFrameworkUpdate):',
            f'    """',
            f'    {framework_type.upper()} Framework Update #{version}',
            f'    Auto-generated by Regulatory Change Monitor on {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}',
            f'',
            f'    This update includes:',
        ]

        if new_chapters:
            lines.append(f'    - {len(new_chapters)} new chapter(s)')
        if new_questions:
            lines.append(f'    - {len(new_questions)} new question(s)')
        if new_objectives:
            lines.append(f'    - {len(new_objectives)} new objective(s)')
        if updated_objectives:
            lines.append(f'    - {len(updated_objectives)} updated objective(s)')
        if updated_questions:
            lines.append(f'    - {len(updated_questions)} updated question(s)')

        lines.extend([
            f'    """',
            f'',
            f'    version = {version}',
            f'    description = {repr(desc)}',
            f'    framework_name = {repr(framework_type)}',
            f'',
        ])

        # get_new_questions
        lines.append('    def get_new_questions(self) -> List[Dict]:')
        if new_questions:
            lines.append('        return [')
            for q in new_questions:
                lines.append('            {')
                for key, value in q.items():
                    lines.append(f'                {repr(key)}: {repr(value)},')
                lines.append('            },')
            lines.append('        ]')
        else:
            lines.append('        return []')
        lines.append('')

        # get_new_chapters
        lines.append('    def get_new_chapters(self) -> List[Dict]:')
        if new_chapters:
            lines.append('        return [')
            for ch in new_chapters:
                lines.append('            {')
                for key, value in ch.items():
                    lines.append(f'                {repr(key)}: {repr(value)},')
                lines.append('            },')
            lines.append('        ]')
        else:
            lines.append('        return []')
        lines.append('')

        # get_new_objectives
        lines.append('    def get_new_objectives(self) -> List[Dict]:')
        if new_objectives:
            lines.append('        return [')
            for obj in new_objectives:
                lines.append('            {')
                for key, value in obj.items():
                    lines.append(f'                {repr(key)}: {repr(value)},')
                lines.append('            },')
            lines.append('        ]')
        else:
            lines.append('        return []')
        lines.append('')

        # get_updated_objectives
        lines.append('    def get_updated_objectives(self) -> List[Dict]:')
        if updated_objectives:
            lines.append('        return [')
            for obj in updated_objectives:
                lines.append('            {')
                for key, value in obj.items():
                    lines.append(f'                {repr(key)}: {repr(value)},')
                lines.append('            },')
            lines.append('        ]')
        else:
            lines.append('        return []')
        lines.append('')

        # get_updated_questions
        if updated_questions:
            lines.append('    def get_updated_questions(self) -> List[Dict]:')
            lines.append('        return [')
            for q in updated_questions:
                lines.append('            {')
                for key, value in q.items():
                    lines.append(f'                {repr(key)}: {repr(value)},')
                lines.append('            },')
            lines.append('        ]')
            lines.append('')

        return '\n'.join(lines) + '\n'

    @staticmethod
    def write_update_file(framework_type: str, version: int, content: str) -> str:
        """
        Write update file to app/seeds/updates/{framework_type}/{type}_update_{version}.py
        Update __init__.py __all__ list. Returns file path.
        """
        # Ensure directory exists
        fw_dir = os.path.join(SEEDS_BASE_DIR, framework_type)
        os.makedirs(fw_dir, exist_ok=True)

        # Write the update file
        filename = f"{framework_type}_update_{version}.py"
        file_path = os.path.join(fw_dir, filename)
        with open(file_path, "w") as f:
            f.write(content)

        # Update __init__.py
        class_name = SeedFileWriterService._make_class_name(framework_type, version)
        init_path = os.path.join(fw_dir, "__init__.py")

        # Read existing __init__.py
        existing_content = ""
        existing_all = []
        if os.path.exists(init_path):
            with open(init_path, "r") as f:
                existing_content = f.read()

            # Parse existing __all__
            import ast
            for node in ast.walk(ast.parse(existing_content)):
                if isinstance(node, ast.Assign):
                    for target in node.targets:
                        if isinstance(target, ast.Name) and target.id == "__all__":
                            if isinstance(node.value, ast.List):
                                for elt in node.value.elts:
                                    if isinstance(elt, ast.Constant):
                                        existing_all.append(elt.value)

        # Add new class to __all__ if not already there
        if class_name not in existing_all:
            existing_all.append(class_name)

        # Generate new __init__.py
        module_name = f"{framework_type}_update_{version}"
        import_lines = []
        for cls_name in existing_all:
            # Derive module name from class name
            parts = []
            for i, c in enumerate(cls_name):
                if c.isupper() and i > 0:
                    parts.append('_')
                parts.append(c.lower())
            mod_name = ''.join(parts)
            import_lines.append(f"from .{mod_name} import {cls_name}")

        init_content = '\n'.join(import_lines) + '\n\n'
        init_content += f"__all__ = {repr(existing_all)}\n"

        with open(init_path, "w") as f:
            f.write(init_content)

        logger.info(f"Written seed update file: {file_path}")
        return file_path

    @staticmethod
    def validate_update_file(file_path: str) -> bool:
        """Dynamic import + instantiate to verify valid BaseFrameworkUpdate subclass."""
        try:
            # Convert file path to module path
            # e.g. /app/seeds/updates/cra/cra_update_2.py -> app.seeds.updates.cra.cra_update_2
            rel_path = os.path.relpath(file_path, os.path.dirname(SEEDS_BASE_DIR + "/.."))
            module_path = rel_path.replace(os.sep, ".").replace(".py", "")

            # Ensure it starts with 'app.'
            if not module_path.startswith("app."):
                module_path = "app." + module_path

            module = importlib.import_module(module_path)

            # Find the update class
            from ..seeds.updates.base_framework_update import BaseFrameworkUpdate
            found_class = False
            for attr_name in dir(module):
                attr = getattr(module, attr_name)
                if (isinstance(attr, type) and
                    issubclass(attr, BaseFrameworkUpdate) and
                    attr != BaseFrameworkUpdate):
                    # Try to instantiate
                    instance = attr()
                    assert hasattr(instance, 'version')
                    assert hasattr(instance, 'description')
                    assert hasattr(instance, 'framework_name')
                    found_class = True
                    break

            return found_class

        except Exception as e:
            logger.error(f"Validation failed for {file_path}: {e}")
            return False

    @staticmethod
    def get_next_version(framework_type: str) -> int:
        """Determine the next version number for a framework's update files."""
        fw_dir = os.path.join(SEEDS_BASE_DIR, framework_type)
        if not os.path.exists(fw_dir):
            return 1

        max_version = 0
        for filename in os.listdir(fw_dir):
            if filename.startswith(f"{framework_type}_update_") and filename.endswith(".py"):
                try:
                    version = int(filename.replace(f"{framework_type}_update_", "").replace(".py", ""))
                    max_version = max(max_version, version)
                except ValueError:
                    pass

        return max_version + 1

    @staticmethod
    def _make_class_name(framework_type: str, version: int) -> str:
        """Generate class name from framework type and version."""
        # e.g., "cra" -> "CRAUpdate2", "nis2_directive" -> "NIS2DirectiveUpdate1"
        parts = framework_type.split("_")
        class_prefix = "".join(p.upper() if len(p) <= 3 else p.capitalize() for p in parts)
        return f"{class_prefix}Update{version}"
