# submission_service.py
import json
import uuid
import smtplib
import os
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from datetime import datetime
from sqlalchemy.orm import Session

from app.models import models
from app.repositories import submission_repository, certificate_repository

logger = logging.getLogger(__name__)


def create_and_send_submission(
    db: Session,
    current_user,
    certificate_id: uuid.UUID,
    authority_name: str,
    recipient_emails: list,
    subject: str = None,
    body: str = None,
) -> models.CertificateSubmission:
    """Create a submission record and attempt to send the certificate via email."""
    # Validate certificate exists and belongs to user's org
    cert = certificate_repository.get_certificate_by_id(db, certificate_id)
    if not cert:
        raise ValueError("Certificate not found")
    if cert.organisation_id != current_user.organisation_id and current_user.role_name != "super_admin":
        raise ValueError("Access denied")
    if not cert.pdf_data:
        raise ValueError("Certificate PDF not available")

    # Get framework and org info for email
    framework = db.query(models.Framework).filter(models.Framework.id == cert.framework_id).first()
    organisation = db.query(models.Organisations).filter(models.Organisations.id == cert.organisation_id).first()

    framework_name = framework.name if framework else "Unknown"
    org_name = organisation.name if organisation else "Unknown"

    # Default subject/body if not provided
    if not subject:
        subject = f"Compliance Certificate Submission - {org_name} - {framework_name} ({cert.certificate_number})"
    if not body:
        body = (
            f"Dear {authority_name},\n\n"
            f"Please find attached the self-assessment compliance certificate for:\n\n"
            f"Organisation: {org_name}\n"
            f"Framework: {framework_name}\n"
            f"Certificate Number: {cert.certificate_number}\n"
            f"Overall Compliance Score: {cert.overall_score:.0f}%\n"
            f"Date Issued: {cert.issued_at.strftime('%B %d, %Y')}\n"
            f"Valid Until: {cert.expires_at.strftime('%B %d, %Y')}\n"
            f"Verification Hash: {cert.verification_hash}\n\n"
            f"This certificate was generated by the CyberBridge Compliance Platform.\n\n"
            f"Best regards,\n"
            f"{current_user.name}\n"
            f"{org_name}"
        )

    # Create submission record
    sub_data = {
        "certificate_id": certificate_id,
        "organisation_id": current_user.organisation_id,
        "submitted_by_user_id": current_user.id,
        "authority_name": authority_name,
        "recipient_emails": json.dumps(recipient_emails),
        "submission_method": "email",
        "status": "draft",
        "subject": subject,
        "body": body,
    }
    submission = submission_repository.create_submission(db, sub_data)

    # Attempt to send email
    email_sent = _send_certificate_email(
        recipient_emails=recipient_emails,
        subject=subject,
        body=body,
        pdf_data=cert.pdf_data,
        cert_number=cert.certificate_number,
    )

    if email_sent:
        submission_repository.update_submission_status(db, submission.id, "sent", datetime.utcnow())
    else:
        # Still mark as draft — user can retry or note that email config is not set up
        logger.warning(f"Email sending failed for submission {submission.id}, marked as draft")

    db.refresh(submission)
    return submission


def _send_certificate_email(
    recipient_emails: list,
    subject: str,
    body: str,
    pdf_data: bytes,
    cert_number: str,
) -> bool:
    """Send certificate PDF via SMTP. Returns True if sent successfully."""
    smtp_host = os.getenv("SMTP_HOST")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER")
    smtp_pass = os.getenv("SMTP_PASS")
    smtp_from = os.getenv("SMTP_FROM", smtp_user)

    if not smtp_host or not smtp_user:
        logger.info("SMTP not configured — skipping email send")
        return False

    try:
        msg = MIMEMultipart()
        msg["From"] = smtp_from
        msg["To"] = ", ".join(recipient_emails)
        msg["Subject"] = subject

        msg.attach(MIMEText(body, "plain"))

        # Attach PDF
        pdf_attachment = MIMEApplication(pdf_data, _subtype="pdf")
        pdf_attachment.add_header("Content-Disposition", "attachment", filename=f"{cert_number}.pdf")
        msg.attach(pdf_attachment)

        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.send_message(msg)

        logger.info(f"Certificate email sent to {recipient_emails}")
        return True
    except Exception as e:
        logger.error(f"Failed to send certificate email: {e}")
        return False
